name: Dev Branch CI/CD

on:
  push:
    branches:
      - mydev

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER_NAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        if: ${{ success() }}
        run: docker build -t sanoj8860/reactjs-app:${{ github.sha }} .

      - name: Publish Docker Image to Docker Hub
        if: ${{ success() }}
        run: docker push sanoj8860/reactjs-app:${{ github.sha }}

      - name: Deploy
        if: ${{ success() }}
        run: |
          echo "Deploying to development server"
          ssh user@dev-server 'docker pull sanoj8860/reactjs-app:${{ github.sha }} && docker rm -f reactContainer && docker run -d -p 3000:80 --name reactContainer sanoj8860/reactjs-app:${{ github.sha }}'
